# Generated by Django 2.1.5 on 2019-01-20 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartproductmap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='creation_date',
            new_name='created',
        ),
    ]
